### ISSUE TITLE
Rust diff

### ISSUE THREAD

**Issue by mirecl** [LesnyRumcajs/grpc_bench#105]
Hi, what different between rust impl gRPC:

rust_tonic_st
rust_tonic_mt

**Comment by LesnyRumcajs** [comment]
Hi @mirecl , it's the `rt-threaded` feature of `tokio` in `Cargo.toml` which enables the multi-threaded, work-stealing scheduler (https://tokio-rs.github.io/tokio/doc/tokio/), essential for multi-core tests.
