### ISSUE TITLE
Errors running benchmark in CI with "RUN BENCHMARK" issue

### ISSUE THREAD

**Issue by nico-abram** [LesnyRumcajs/grpc_bench#126]
I tried running the benchmark in CI(In a fork) and got a number of errors:

```
==> Error building ./lua_grpc_st_bench
==> Error building ./kotlin_grpc_bench
 ==> Error building ./java_aot_bench
==> Error building ./haskell_mu_bench
```

They all seem to be related to running out of disk space

**Comment by LesnyRumcajs** [comment]
@nico-abram Thanks for noticing, I'll look it up.

**Comment by LesnyRumcajs** [comment]
@nico-abram should be fine since we disabled Lua "temporarily" (who am I kidding?). Could you please confirm?
