### ISSUE TITLE
Q: Client-side source code

### ISSUE THREAD

**Issue by HarpPDX** [LesnyRumcajs/grpc_bench#131]
Where is the source code for the client, infoblox/ghz?

**Comment by LesnyRumcajs** [comment]
Hi @HarpPDX 
We use this image from Dockerhub: https://hub.docker.com/r/infoblox/ghz/
It uses 0.50.0 release of https://github.com/bojand/ghz .

Does it answer your question?

**Comment by HarpPDX** [comment]
Thank you @LesnyRumcajs.
