### ISSUE TITLE
Little confusion with benchmark results

### ISSUE THREAD

**Issue by sergus00** [LesnyRumcajs/grpc_bench#149]
So, I am confused, why there's a huge difference in benchmarking results between:
2021 04 13 bench results 
and
2021 05 10 bench results
What changed in setup or versions?

**Comment by LesnyRumcajs** [comment]
Hi @sergus00 . Thanks for your interest. The setup is there in the test preamble. A notable difference comes from:
```
GRPC_CLIENT_CONNECTIONS=5
GRPC_CLIENT_CONCURRENCY=50
```
changed to
```
GRPC_CLIENT_CONNECTIONS=50
GRPC_CLIENT_CONCURRENCY=1000
```
which impacted all the suites.

From a quick glimpse through the commits, Java implementations stopped using Direct Executor plus various improvements / version bumps across other technologies.

Does it answer your question?
