### ISSUE TITLE
Addressing encoder/decoder performance in benchmarks

### ISSUE THREAD

**Issue by night-crawler** [LesnyRumcajs/grpc_bench#169]
First of all, thank you for your efforts!

Currently, I'm researching the possibility of employing Rust for some performance-critical microservices in our infrastructure. Unfortunately, the gRPC greeter does not seem to be enough to reveal the actual performance of concrete decoder/encoder implementations. 

I have a [repository](https://github.com/night-crawler/prometheus-kafka) that mimics a thing we mostly do: read something from gRPC, give it a bit of processing, and put it to Kafka.

On average the dry-run (skipping Kafka) gives me:
- 120K RPS with an [empty message](https://github.com/night-crawler/prometheus-kafka/blob/main/payload/empty.json)
- 55K RPS with a [medium message](https://github.com/night-crawler/prometheus-kafka/blob/main/payload/medium.json)
- 10K RPS with a [large message](https://github.com/night-crawler/prometheus-kafka/blob/main/payload/large.json)

Profiling shows me this picture (I filtered not interesting things out):

![image](https://user-images.githubusercontent.com/1235203/148537531-7e7dc36b-481f-4141-adfc-73e6e6b1f192.png)

It seems that the prost spends a lot of time processing the data. It's not a surprise, but it's interesting to compare it against some other implementations.

What do you think about adding some heavy production-like data structures that can help reveal more real-world-like performance?

Thank you.

**Comment by Trisfald** [comment]
Hi @night-crawler 
Currently you can change the request payload with the env variable `GRPC_REQUEST_PAYLOAD`. We have a few example files, you could try using `GRPC_REQUEST_PAYLOAD=10kB`; its content is just a large string though. 
If you need more complex payloads I suggest using your own json-like file (maybe even making a PR 👍 ).

**Comment by Trisfald** [comment]
I've given some more though to this issue and I came up with #171 . It's not complete yet, but it might be what you are looking for.

**Comment by night-crawler** [comment]
@Trisfald, thank you!

If you haven't seen them yet, I added a PR with fixes for java. On Ryzen 5900HS, I got these results (30KB complex_proto sample, echo-like mode):

```
-----------------------------------------------------------------------------------------------------------------------------------------
| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
-----------------------------------------------------------------------------------------------------------------------------------------
| rust_tonic_mt               |   34824 |       13.91 ms |       23.22 ms |       31.88 ms |      136.44 ms |  180.94% |     44.85 MiB |
| java_hotspot_grpc_pgc       |    7232 |      118.18 ms |      567.13 ms |      736.19 ms |         1.15 s |  127.34% |    257.13 MiB |
| java_hotspot_grpc_sgc       |    7106 |      120.70 ms |      578.00 ms |      713.13 ms |         1.15 s |  117.16% |     124.9 MiB |
| java_hotspot_grpc_g1gc      |    7079 |      120.85 ms |      570.75 ms |      721.39 ms |         1.09 s |  109.28% |     186.7 MiB |
| java_hotspot_grpc_she       |    7057 |      119.34 ms |      535.67 ms |      721.47 ms |         1.10 s |  120.92% |    451.93 MiB |
| java_micronaut_workstealing |    7042 |      120.98 ms |      568.37 ms |      712.52 ms |         1.07 s |  137.41% |    297.83 MiB |
| java_micronaut              |    7029 |      120.28 ms |      548.43 ms |      713.85 ms |         1.14 s |  143.72% |    265.87 MiB |
| java_hotspot_grpc_zgc       |    7010 |      121.63 ms |      550.23 ms |      729.39 ms |         1.10 s |  149.15% |     431.7 MiB |
| java_openj9_grpc_gencon     |    6955 |      124.88 ms |      571.52 ms |      762.51 ms |         1.11 s |  130.14% |    210.65 MiB |
| kotlin_grpc                 |    6935 |      124.10 ms |      566.90 ms |      753.13 ms |         1.14 s |  161.54% |     265.9 MiB |
| java_aot                    |    6581 |      130.10 ms |      606.66 ms |      797.17 ms |         1.22 s |  210.47% |    387.75 MiB |
| java_quarkus                |    1355 |        0.79 ms |      550.09 ms |      676.31 ms |         1.05 s |       0% |         0 MiB |
-----------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by Trisfald** [comment]
Quite interesting results @night-crawler . The change in protobuf's structure makes a huge difference indeed..

**Comment by LesnyRumcajs** [comment]
@Trisfald looks like a quite decent idea! Thanks!

@night-crawler More complex scenario with bigger payload will definitely change the results as the biggest load will move from purely protocol to protobufs - and it will in fact assess the protobuf serde performance. But given that it's configurable with @Trisfald PR it should be completely fine.
