### ISSUE TITLE
2022 Results not linking to source code hash

### ISSUE THREAD

**Issue by brunoborges** [LesnyRumcajs/grpc_bench#181]
The latest results in 2022 benchmark [1] don't have a link to the hash of the code that was used to produce these results.

https://github.com/LesnyRumcajs/grpc_bench/wiki/2022-01-11-bench-results

**Comment by Trisfald** [comment]
Hi @brunoborges 
The hash reported in the page is `b4f96b6` (before a merge commit) which can be browsed at `https://github.com/LesnyRumcajs/grpc_bench/tree/b4f96b608c07e6ffe15a276cb7562ca1130e5065`

Let me know if I've misunderstood your point!

**Comment by brunoborges** [comment]
Silly me. I didn't see the little hash in the wiki page, because it is not a hyperlink.

My bad!
