### ISSUE TITLE
Set up scala-steward?

### ISSUE THREAD

**Issue by hepin1989** [LesnyRumcajs/grpc_bench#208]
https://github.com/scala-steward-org/scala-steward will support automaticly update the dependencies.

**Comment by LesnyRumcajs** [comment]
Sure, sounds good to me!

**Comment by LesnyRumcajs** [comment]
Done: https://github.com/scala-steward-org/repos/pull/969

**Comment by hepin1989** [comment]
> Done: https://github.com/scala-steward-org/repos/pull/969

Will need a config file in this project root too

**Comment by LesnyRumcajs** [comment]
Can you please elaborate?

**Comment by hepin1989** [comment]
The scala project lives in a subfolder and will need a configuration file IIRC .scala-steward.conf？

**Comment by hepin1989** [comment]
https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md

**Comment by LesnyRumcajs** [comment]
@hepin1989 I changed the update frequency to 90 days to limit the PR deluge the steward is doing. :)

**Comment by LesnyRumcajs** [comment]
@hepin1989 in general we update them ad hoc, that being said only @Trisfald has access to a dedicated machine that was always running them.
