### ISSUE TITLE
Add Erlang benchmark

### ISSUE THREAD

**Issue by Trisfald** [LesnyRumcajs/grpc_bench#22]
Add an Erlang grpc benchmark.

The library is here: https://github.com/bluehouse-technology/grpc

- [ ] gRPC server implementation
- [ ] Dockerfile to build an image with the gRPC server
- [ ] update build.sh, clean.sh and bench.sh scripts

**Comment by fenollp** [comment]
This should be a more actively maintained lib https://github.com/tsloughter/grpcbox
I might work on adding it as a benchmark here sometime soon :)

**Comment by LesnyRumcajs** [comment]
@fenollp We'd be very glad for a contribution, I personally don't know Erlang so the results would most likely be sub-optimal. :)
