### ISSUE TITLE
Delete OpenJ9 test cases

### ISSUE THREAD

**Issue by gcnyin** [LesnyRumcajs/grpc_bench#236]
Almost no one is using OpenJ9 in production, it hardly makes sense.

**Comment by LesnyRumcajs** [comment]
Not sure here, I don't really follow Java world. According to the latest results, OpenJ9 is leading across other Java implementations. It's still maintained as well and most likely more used than e.g. D implementation. Perhaps @bmarwell or @brunoborges can pronounce on this matter?

**Comment by brunoborges** [comment]
It is still quite a valid runtime. Just because one person doesn't use it, does not mean no one is using :-)

**Comment by gcnyin** [comment]
Got it.

**Comment by LesnyRumcajs** [comment]
Thank you @brunoborges !
