### ISSUE TITLE
Update Rust Thruster servers

### ISSUE THREAD

**Issue by LesnyRumcajs** [LesnyRumcajs/grpc_bench#351]
Unfortunately, I failed to easily update the thruster dependencies; I'll leave it as a separate issue to do.

_Originally posted by @LesnyRumcajs in https://github.com/LesnyRumcajs/grpc_bench/issues/350#issuecomment-1605566285_
            
It would be lovely to update the Thruster implementation (unless it is no longer maintained, then it should be deleted)

**Comment by LesnyRumcajs** [comment]
@trezm You may be interested in this. :)

**Comment by trezm** [comment]
Ah okay, I'll add it to my list!! Thank you!
