### ISSUE TITLE
Add multiple core benchmark

### ISSUE THREAD

**Issue by Tarang** [LesnyRumcajs/grpc_bench#57]
Hey!

Great work on this benchmark! This benchmark is very timely as I was actually benching a few libraries the past few days as well! I noticed the results pretty much match what you get, but the results change when you use multiple cores.

So there should also be a multi-core benchmark as well a single core one. To see how each implementation maintains uses threads as it would represent a production environment more closely.

**Comment by Trisfald** [comment]
Hello! 
I agree with your suggestion. 

As a first step I opened #58 . The PR let the user specify the number of cpu to allocate for the server. 

I tried it locally and I wasn't able to use more than 100% cpu with the following tests:

- rust_tonic
- cpp_grpc
- lua_grpc
- node_grpc
- swift_grpc
- crystal_grpc
- rust_thruster

We could try either to make all implementations supports multiple cpus by default, or have two versions one singlethreaded and one multithreaded.

**Comment by LesnyRumcajs** [comment]
Yes, definitely. I think we should strive to have implementation that works well both in single and multi-core environment but if it's not possible then some of those can have `_multi` variants.

It's worth noting that multi-core benchmarks may need a proper rig to run them - e.g. Rust Tonic tonic server at 1 core limit needs `ghz` running on 6 cores to saturate it. If it would perfectly scale (both `ghz` and server) we would need free 14 cores just for the benchmark.

**Comment by Trisfald** [comment]
We have added results for single cpu and three cpus test runs in the [wiki](https://github.com/LesnyRumcajs/grpc_bench/wiki/2020.07.24---bench-resultsl)
It is also now possible to easily run multithreaded benchmarks by setting the environment variable `GRPC_SERVER_CPUS`.

@Tarang Do you agree we can close this issue?

**Comment by Tarang** [comment]
Yup thanks @Trisfald. Super interesting results! Thanks for integrating multiple cores in. This is now hopefully how well benchmark gRPC going forward and see how each of the libraries improves over time!
